flyway.schemas=dodo
flyway.table=schema_history

flyway.locations=filesystem:/migrations/sql

flyway.baselineOnMigrate=true
flyway.validateOnMigrate=true
flyway.outOfOrder=false
flyway.encoding=UTF-8
flyway.sqlMigrationPrefix=V
flyway.repeatableSqlMigrationPrefix=R
flyway.placeholderPrefix=${  
flyway.placeholderSuffix=}

flyway.cleanDisabled=true
flyway.connectRetries=60
flyway.connectRetriesInterval=5